In [1]:
import os
import joblib
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MaxAbsScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import spacy
import optuna
import mlflow
import mlflow.sklearn

# MLflow / DagShub tracking setup
os.environ["MLFLOW_TRACKING_USERNAME"] = "Roy7721"
os.environ["MLFLOW_TRACKING_PASSWORD"] = "bc912b7d58bd2aca05abdc192e010414493a3886"
mlflow.set_tracking_uri("https://dagshub.com/Roy7721/yt_comment_analysis.mlflow")
mlflow.set_experiment("LogisticRegression HP Tuning with Custom Features")

C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


<Experiment: artifact_location='mlflow-artifacts:/84a8f7afc8434d5398ba8feeab10e4f4', creation_time=1784660079577, effective_trace_archival_retention=None, experiment_id='14', last_update_time=1784660079577, lifecycle_stage='active', name='LogisticRegression HP Tuning with Custom Features', tags={'mlflow.experimentKind': 'custom_model_development'}, trace_location=None, workspace='default'>

In [2]:
# Load dataset
dataset = pd.read_csv('dataset.csv')

# Drop rows with NaN values in 'clean_comment'
cleaned_dataset = dataset.dropna()

In [3]:
# Separate features and target
X_cleaned = cleaned_dataset['clean_comment']
y_cleaned = cleaned_dataset['category']

# Split the cleaned data into train and test sets (80-20 split)
X_train_cleaned, X_test_cleaned, y_train_cleaned, y_test_cleaned = train_test_split(X_cleaned, y_cleaned, test_size=0.2, random_state=42)


In [4]:
# Load spacy language model for POS tagging
nlp = spacy.load('en_core_web_sm')

In [5]:
# All 17 universal POS tags, in a FIXED order.
# Looping over this (instead of set(pos_tags)) guarantees every comment produces the
# same 17 POS columns in the same order -> train, test, and future data always line up.
UNIVERSAL_POS = ['ADJ', 'ADP', 'ADV', 'AUX', 'CCONJ', 'DET', 'INTJ', 'NOUN', 'NUM',
                 'PART', 'PRON', 'PROPN', 'PUNCT', 'SCONJ', 'SYM', 'VERB', 'X']

# Function to extract custom features
def extract_custom_features(text):
    doc = nlp(text)
    word_list = [token.text for token in doc]

    # 1. Comment Length (number of characters)
    comment_length = len(text)

    # 2. Word Count
    word_count = len(word_list)

    # 3. Average Word Length
    avg_word_length = sum(len(word) for word in word_list) / word_count if word_count > 0 else 0

    # 4. Unique Word Count
    unique_word_count = len(set(word_list))

    # 5. Lexical Diversity
    lexical_diversity = unique_word_count / word_count if word_count > 0 else 0

    # 6. Count of POS Tags
    pos_count = len([token.pos_ for token in doc])

    # 7. Proportion of POS Tags - loop over the FIXED list (not set()) so every comment
    #    yields all 17 columns in the same order; tags not present come out as 0.
    pos_tags = [token.pos_ for token in doc]
    if word_count > 0:
        pos_proportion = {tag: pos_tags.count(tag) / word_count for tag in UNIVERSAL_POS}
    else:
        pos_proportion = {tag: 0 for tag in UNIVERSAL_POS}

    return {
        'comment_length': comment_length,
        'word_count': word_count,
        'avg_word_length': avg_word_length,
        'unique_word_count': unique_word_count,
        'lexical_diversity': lexical_diversity,
        'pos_count': pos_count,
        **pos_proportion  # Flattening the POS proportions
    }

In [6]:
# Apply the custom feature extraction
train_custom_features = pd.DataFrame([extract_custom_features(text) for text in X_train_cleaned])
test_custom_features = pd.DataFrame([extract_custom_features(text) for text in X_test_cleaned])

In [7]:
train_custom_features.head()

,comment_length,word_count,avg_word_length,unique_word_count,lexical_diversity,pos_count,ADJ,ADP,ADV,AUX,...,NOUN,NUM,PART,PRON,PROPN,PUNCT,SCONJ,SYM,VERB,X
0,51,7,6.428571,7,1.000000,7,0.000000,0.142857,0.142857,0.142857,...,0.142857,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.428571,0.0
1,36,6,5.166667,6,1.000000,6,0.000000,0.000000,0.000000,0.000000,...,0.333333,0.000000,0.000000,0.166667,0.166667,0.0,0.0,0.0,0.333333,0.0
2,64,9,6.222222,9,1.000000,9,0.222222,0.000000,0.111111,0.000000,...,0.444444,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.222222,0.0
3,108,15,6.266667,14,0.933333,15,0.200000,0.000000,0.000000,0.000000,...,0.466667,0.066667,0.066667,0.000000,0.000000,0.0,0.0,0.0,0.200000,0.0
4,6,1,6.000000,1,1.000000,1,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0


In [8]:
# Replace NaN values in POS tag proportions with 0
train_custom_features.fillna(0, inplace=True)
test_custom_features.fillna(0, inplace=True)

In [9]:
test_custom_features.isnull().sum()

comment_length       0
word_count           0
avg_word_length      0
unique_word_count    0
lexical_diversity    0
pos_count            0
ADJ                  0
ADP                  0
ADV                  0
AUX                  0
CCONJ                0
DET                  0
INTJ                 0
NOUN                 0
NUM                  0
PART                 0
PRON                 0
PROPN                0
PUNCT                0
SCONJ                0
SYM                  0
VERB                 0
X                    0
dtype: int64

In [10]:
# Apply TfidfVectorizer with bigram setting and max_features=10000
ngram_range = (1, 2)
max_features = 10000
tfidf = TfidfVectorizer(ngram_range=ngram_range, max_features=max_features)
X_train_tfidf = tfidf.fit_transform(X_train_cleaned)
X_test_tfidf = tfidf.transform(X_test_cleaned)

In [11]:
# Keep TF-IDF SPARSE - no .toarray() here.
# The TF-IDF matrix is ~99.8% zeros; densifying it would cost ~2.35 GB and force the
# solver to multiply by zero hundreds of millions of times per iteration.
#
# All we need before stacking is that the small 23-column custom-feature block has the
# same columns in the same order for train and test.
test_custom_features = test_custom_features.reindex(
    columns=train_custom_features.columns, fill_value=0
)

print('custom feature columns aligned:', list(train_custom_features.columns) == list(test_custom_features.columns))

custom feature columns aligned: True


In [12]:
from scipy.sparse import hstack, csr_matrix

# Combine [sparse TF-IDF | small dense custom-feature block] WITHOUT densifying anything.
# Column order is guaranteed: TF-IDF columns come from the fitted vocabulary (identical for
# train/test), and the custom block was aligned in the previous cell. Sparse matrices carry
# no column names, so the old "feature names must be in the same order" error cannot occur.
X_train_combined = hstack([X_train_tfidf, csr_matrix(train_custom_features.values)]).tocsr()
X_test_combined  = hstack([X_test_tfidf,  csr_matrix(test_custom_features.values)]).tocsr()

dense_mb = X_train_combined.shape[0] * X_train_combined.shape[1] * 8 / 1e6
sparse_mb = (X_train_combined.data.nbytes + X_train_combined.indices.nbytes + X_train_combined.indptr.nbytes) / 1e6
print('train shape :', X_train_combined.shape)
print('test  shape :', X_test_combined.shape)
print(f'sparse size : {sparse_mb:.1f} MB   (dense would be ~{dense_mb:.0f} MB)')
print(f'density     : {X_train_combined.nnz / (X_train_combined.shape[0] * X_train_combined.shape[1]) * 100:.2f}%  non-zero')

train shape : (29329, 10023)
test  shape : (7333, 10023)
sparse size : 9.7 MB   (dense would be ~2352 MB)
density     : 0.27%  non-zero


In [13]:
X_train_combined

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 796623 stored elements and shape (29329, 10023)>

In [14]:
X_train = X_train_combined
X_test = X_test_combined
y_train = y_train_cleaned
y_test = y_test_cleaned

In [15]:
# Function to log results in MLflow
def log_mlflow(model_name, model, X_train, X_test, y_train, y_test, params, trial_number, log_model=False):
    with mlflow.start_run():
        # Log model type and trial number
        mlflow.set_tag("mlflow.runName", f"Trial_{trial_number}_{model_name}_")
        mlflow.set_tag("experiment_type", "algorithm_comparison")

        # Log algorithm name as a parameter
        mlflow.log_param("algo_name", model_name)
        mlflow.log_param("vectorizer_type", "TfidfVectorizer")
        mlflow.log_param("ngram_range", str(ngram_range))
        mlflow.log_param("vectorizer_max_features", max_features)
        mlflow.log_param("scaler", "MaxAbsScaler")

        # Log hyperparameters
        for key, value in params.items():
            mlflow.log_param(key, value)

        # Train model
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        # Log accuracy
        accuracy = accuracy_score(y_test, y_pred)
        mlflow.log_metric("accuracy", accuracy)

        # Log classification report
        classification_rep = classification_report(y_test, y_pred, output_dict=True)
        for label, metrics in classification_rep.items():
            if isinstance(metrics, dict):
                for metric, value in metrics.items():
                    mlflow.log_metric(f"{label}_{metric}", value)

        # Only log the model artifact for the best run to stay within DagShub free tier limits
        if log_model:
            # Persist locally first so a long train is never lost to a logging failure
            joblib.dump(model, f"{model_name}_best_model.joblib")
            try:
                mlflow.sklearn.log_model(
                    model, f"{model_name}_model",
                    serialization_format=mlflow.sklearn.SERIALIZATION_FORMAT_CLOUDPICKLE,
                )
            except Exception as e:
                print(f"[warn] model artifact logging failed (metrics/params + joblib file are safe): {e}")

        return accuracy

In [16]:
# Step 6: Optuna objective function for Logistic Regression
def objective_logreg(trial):
    # Hyperparameter space to explore
    C = trial.suggest_float('C', 1e-4, 10.0, log=True)  # inverse regularization strength
    # sklearn >= 1.8 deprecated `penalty` in favour of a continuous `l1_ratio` dial:
    #   0.0 = pure L2   |   0.5 = elasticnet blend   |   1.0 = pure L1
    l1_ratio = trial.suggest_float('l1_ratio', 0.0, 1.0)
    # Class imbalance handling - let Optuna decide whether balancing helps
    class_weight = trial.suggest_categorical('class_weight', [None, 'balanced'])

    # Log trial parameters
    params = {
        'C': C,
        'l1_ratio': l1_ratio,
        'class_weight': class_weight,
        'solver': 'saga',   # saga supports the full l1/l2/elasticnet range
        'max_iter': 300
    }

    # MaxAbsScaler -> LogisticRegression pipeline.
    # MaxAbsScaler is sparse-safe (unlike StandardScaler, which would destroy sparsity).
    # No `penalty` argument - l1_ratio fully controls the regularization type.
    model = Pipeline([
        ('scaler', MaxAbsScaler()),
        ('clf', LogisticRegression(C=C, l1_ratio=l1_ratio, class_weight=class_weight,
                                   solver='saga', max_iter=300, random_state=42))
    ])

    # Log each trial as a separate run in MLflow
    accuracy = log_mlflow("LogisticRegression", model, X_train, X_test, y_train, y_test, params, trial.number)

    return accuracy

In [17]:
# Step 7: Run Optuna for Logistic Regression, log the best model, and plot the importance of each parameter
def run_optuna_experiment():
    study = optuna.create_study(direction="maximize")
    study.optimize(objective_logreg, n_trials=50)  # 50 trials

    # Get the best parameters
    best_params = study.best_params
    best_model = Pipeline([
        ('scaler', MaxAbsScaler()),
        ('clf', LogisticRegression(C=best_params['C'],
                                   l1_ratio=best_params['l1_ratio'],
                                   class_weight=best_params['class_weight'],
                                   solver='saga', max_iter=300, random_state=42))
    ])

    # Log the best model with MLflow (only this run uploads the model artifact)
    log_mlflow("LogisticRegression", best_model, X_train, X_test, y_train, y_test, best_params, "Best", log_model=True)

    # Plots are optional - never let a missing optional dependency kill the return value
    try:
        optuna.visualization.plot_param_importances(study).show()
        optuna.visualization.plot_optimization_history(study).show()
    except Exception as e:
        print(f"[warn] optuna plots skipped: {e}")

    print(f"\nBest accuracy: {study.best_value:.4f}")
    print(f"Best params  : {best_params}")

    # Return the best model so it can be inspected outside this function
    return best_model

In [18]:
# Run the experiment for Logistic Regression
best_model = run_optuna_experiment()

[I 2026-07-22 03:06:50,136] A new study created in memory with name: no-name-9817b509-d3fd-4e21-89d3-de95b1bf5e78
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_0_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/e6326f0f8b4449a8b27d7d5971da678a
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 03:23:55,275] Trial 0 finished with value: 0.8703122869221328 and parameters: {'C': 2.2833658272215223, 'l1_ratio': 0.8479244400135727, 'class_weight': None}. Best is trial 0 with value: 0.8703122869221328.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_1_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/d4db8aed67b84687ad35328e03a795f1
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 03:48:36,866] Trial 1 finished with value: 0.8446747579435429 and parameters: {'C': 0.6828195620906322, 'l1_ratio': 0.2724035335474214, 'class_weight': None}. Best is trial 0 with value: 0.8703122869221328.


🏃 View run Trial_2_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/64803bf72e684eb29449bd964198e1ac
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 04:17:07,161] Trial 2 finished with value: 0.820946406654848 and parameters: {'C': 0.4259288476358109, 'l1_ratio': 0.020122128807915862, 'class_weight': None}. Best is trial 0 with value: 0.8703122869221328.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\metrics\_classification.p

🏃 View run Trial_3_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/3401845d52584919a859267b5ea256f6
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 04:18:12,180] Trial 3 finished with value: 0.4331105959361789 and parameters: {'C': 0.00013625271214267462, 'l1_ratio': 0.6005754662353977, 'class_weight': None}. Best is trial 0 with value: 0.8703122869221328.


🏃 View run Trial_4_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/6e75626b94024e86997c18bce53dd987
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 04:19:31,883] Trial 4 finished with value: 0.602072821491886 and parameters: {'C': 0.01430293447540441, 'l1_ratio': 0.8252355246696107, 'class_weight': None}. Best is trial 0 with value: 0.8703122869221328.


🏃 View run Trial_5_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/c23d833c9f5d41ed93de4662031e24a3
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 04:20:47,069] Trial 5 finished with value: 0.7325787535797081 and parameters: {'C': 0.09665139419819788, 'l1_ratio': 0.30252471436922523, 'class_weight': None}. Best is trial 0 with value: 0.8703122869221328.


🏃 View run Trial_6_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/bd1f4550f782453989952859278b91a9
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 04:22:19,056] Trial 6 finished with value: 0.7393972453293332 and parameters: {'C': 0.10703078117694634, 'l1_ratio': 0.532149486088007, 'class_weight': None}. Best is trial 0 with value: 0.8703122869221328.


🏃 View run Trial_7_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/f52caa52b1e04db3a27da6470b6cb3ab
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 05:05:35,804] Trial 7 finished with value: 0.8341742806491205 and parameters: {'C': 2.2056172925045567, 'l1_ratio': 0.08082258385078545, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8703122869221328.


🏃 View run Trial_8_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/77ccbd81347f4a21930276e8c644530c
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 05:06:38,163] Trial 8 finished with value: 0.5363425610255012 and parameters: {'C': 0.004286176948652284, 'l1_ratio': 0.9014598447683593, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8703122869221328.


🏃 View run Trial_9_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/f0fa0c7c511b4afa86c8bb5646dffdd5
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 05:07:55,463] Trial 9 finished with value: 0.5379789990454111 and parameters: {'C': 0.008621859378775666, 'l1_ratio': 0.9128417386641664, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8703122869221328.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_10_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/b6988cbd24de41de8b299001c96f02ab
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 05:40:40,748] Trial 10 finished with value: 0.8356743488340379 and parameters: {'C': 8.646491808500661, 'l1_ratio': 0.6514295416524691, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8703122869221328.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_11_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/392b5a53b7924ec29753c9e9dee6c1ae
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 06:12:58,621] Trial 11 finished with value: 0.8512205100231829 and parameters: {'C': 1.1417907678769295, 'l1_ratio': 0.30707621061842755, 'class_weight': None}. Best is trial 0 with value: 0.8703122869221328.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_12_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/ec0ca68489c140be8b9ee34a2788bcbc
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 06:52:23,932] Trial 12 finished with value: 0.8360834583390154 and parameters: {'C': 6.917317392264295, 'l1_ratio': 0.39927020484588, 'class_weight': None}. Best is trial 0 with value: 0.8703122869221328.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_13_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/30e4ff30a9ba450182faa2bf4cbafd18
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 06:56:14,670] Trial 13 finished with value: 0.8817673530615028 and parameters: {'C': 0.7726635147868015, 'l1_ratio': 0.9958146357741877, 'class_weight': None}. Best is trial 13 with value: 0.8817673530615028.


🏃 View run Trial_14_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/214b8bfe76654d63b0b6a787d8e6fdf3
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 06:58:14,419] Trial 14 finished with value: 0.7894449747715805 and parameters: {'C': 0.153005209625833, 'l1_ratio': 0.9876509707619067, 'class_weight': None}. Best is trial 13 with value: 0.8817673530615028.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_15_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/df72de23e7d746789dd9e9e404e1aa7b
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 07:14:03,049] Trial 15 finished with value: 0.8670394108823128 and parameters: {'C': 2.0241050713260234, 'l1_ratio': 0.743193085929196, 'class_weight': None}. Best is trial 13 with value: 0.8817673530615028.


🏃 View run Trial_16_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/679d08e263cb47348fd4705d96d4e7ba
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 07:15:11,573] Trial 16 finished with value: 0.6656211645983908 and parameters: {'C': 0.0488886958319361, 'l1_ratio': 0.7624401797424758, 'class_weight': None}. Best is trial 13 with value: 0.8817673530615028.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\metrics\_classification.

🏃 View run Trial_17_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/6c5d14513bdb4bf1a7ee9c2ffbf883a0
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 07:16:32,316] Trial 17 finished with value: 0.4331105959361789 and parameters: {'C': 0.001069240819748777, 'l1_ratio': 0.95006242303781, 'class_weight': None}. Best is trial 13 with value: 0.8817673530615028.


🏃 View run Trial_18_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/a816db9a9a434960a2c1e717f66270fc
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 07:18:17,929] Trial 18 finished with value: 0.8429019500886404 and parameters: {'C': 0.32744818398580045, 'l1_ratio': 0.8228047553079824, 'class_weight': 'balanced'}. Best is trial 13 with value: 0.8817673530615028.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_19_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/3c8f250e18df42efad17ba39e2317cff
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 07:38:42,216] Trial 19 finished with value: 0.8618573571525978 and parameters: {'C': 2.726245331914494, 'l1_ratio': 0.6877773865825397, 'class_weight': None}. Best is trial 13 with value: 0.8817673530615028.


🏃 View run Trial_20_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/ea9192ffa81f440b877a8b1a74bf4ab7
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 07:40:07,174] Trial 20 finished with value: 0.6604391108686758 and parameters: {'C': 0.04388099498767122, 'l1_ratio': 0.8590195840621564, 'class_weight': None}. Best is trial 13 with value: 0.8817673530615028.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_21_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/9e50328c5af6441ab91480edc17669e6
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 07:57:46,992] Trial 21 finished with value: 0.8656757125323878 and parameters: {'C': 2.315410879560393, 'l1_ratio': 0.74078849617496, 'class_weight': None}. Best is trial 13 with value: 0.8817673530615028.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_22_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/21e385cac4724762a70d3b236ec898d6
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 08:02:41,736] Trial 22 finished with value: 0.8870857766262102 and parameters: {'C': 1.1199134843600127, 'l1_ratio': 0.9990014673384794, 'class_weight': None}. Best is trial 22 with value: 0.8870857766262102.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_23_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/8b7a70b6f8ab47e9a545acf34fd66c33
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 08:05:12,212] Trial 23 finished with value: 0.8482203736533479 and parameters: {'C': 0.3374657477353009, 'l1_ratio': 0.9977263933842804, 'class_weight': None}. Best is trial 22 with value: 0.8870857766262102.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_24_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/4a04c9f8ce6945c49d48376887c299d6
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 08:25:17,995] Trial 24 finished with value: 0.8483567434883403 and parameters: {'C': 6.991746741529294, 'l1_ratio': 0.8927025540337189, 'class_weight': None}. Best is trial 22 with value: 0.8870857766262102.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_25_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/431c9293bac6455690ab6a919b1e188f
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 08:29:39,836] Trial 25 finished with value: 0.8843583799263602 and parameters: {'C': 0.8773954381402476, 'l1_ratio': 0.9945766865960657, 'class_weight': None}. Best is trial 22 with value: 0.8870857766262102.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_26_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/905c76ff103b4f84910abdf2e31364df
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 08:33:47,575] Trial 26 finished with value: 0.8812218737215328 and parameters: {'C': 0.7931927295832971, 'l1_ratio': 0.9986033221846791, 'class_weight': 'balanced'}. Best is trial 22 with value: 0.8870857766262102.


🏃 View run Trial_27_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/665efd9dd0c54515bd08258029f0e776
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 08:35:19,026] Trial 27 finished with value: 0.816582571935088 and parameters: {'C': 0.2235577788597511, 'l1_ratio': 0.9280015157810532, 'class_weight': None}. Best is trial 22 with value: 0.8870857766262102.


🏃 View run Trial_28_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/3db0272bcb194696af59f8f654698d08
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 08:41:53,452] Trial 28 finished with value: 0.8776762580117278 and parameters: {'C': 0.9283277392923911, 'l1_ratio': 0.813087290370046, 'class_weight': None}. Best is trial 22 with value: 0.8870857766262102.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_29_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/a0e9bd45db864544b5b166248cab7d84
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 09:00:22,075] Trial 29 finished with value: 0.8587208509477704 and parameters: {'C': 4.470645734756511, 'l1_ratio': 0.8619872013186711, 'class_weight': None}. Best is trial 22 with value: 0.8870857766262102.


🏃 View run Trial_30_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/b0b04c13275447d9bf8adc921f95ca9e
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 09:01:37,999] Trial 30 finished with value: 0.6609845902086459 and parameters: {'C': 0.04274992183679089, 'l1_ratio': 0.9384526411128891, 'class_weight': None}. Best is trial 22 with value: 0.8870857766262102.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_31_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/42d6760df26b4326aa64ebbf186a908e
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 09:06:37,653] Trial 31 finished with value: 0.8827219419064503 and parameters: {'C': 0.9222961339045389, 'l1_ratio': 0.9956367150867496, 'class_weight': 'balanced'}. Best is trial 22 with value: 0.8870857766262102.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_32_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/52e8c5ee41f443548be4ac0632848919
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 09:10:38,409] Trial 32 finished with value: 0.8746761216418928 and parameters: {'C': 0.6021771157721626, 'l1_ratio': 0.9863406921972361, 'class_weight': 'balanced'}. Best is trial 22 with value: 0.8870857766262102.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_33_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/bfe25a252d12463f99051941f06b7b8c
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 09:19:39,083] Trial 33 finished with value: 0.8771307786717578 and parameters: {'C': 1.3318267487188928, 'l1_ratio': 0.931572946534012, 'class_weight': 'balanced'}. Best is trial 22 with value: 0.8870857766262102.


🏃 View run Trial_34_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/31ccf864f1814266a70e9d759c2b3a33
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 09:22:29,860] Trial 34 finished with value: 0.8584481112777853 and parameters: {'C': 0.4899281157827976, 'l1_ratio': 0.8056803670651117, 'class_weight': 'balanced'}. Best is trial 22 with value: 0.8870857766262102.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_35_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/46e2940962364d40a56d9a1c2c5a8f43
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 09:40:11,316] Trial 35 finished with value: 0.8572207827628529 and parameters: {'C': 4.03515810517097, 'l1_ratio': 0.8764137083096682, 'class_weight': 'balanced'}. Best is trial 22 with value: 0.8870857766262102.


🏃 View run Trial_36_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/d9e6c663846b42ccbbfb359465a2b1b4
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 09:42:04,765] Trial 36 finished with value: 0.8085367516705305 and parameters: {'C': 0.19816731228060516, 'l1_ratio': 0.9576304185811721, 'class_weight': None}. Best is trial 22 with value: 0.8870857766262102.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_37_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/8f08dc000a5147fbbe2e6426f757e003
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 09:51:27,015] Trial 37 finished with value: 0.8739942724669303 and parameters: {'C': 1.1826584651565966, 'l1_ratio': 0.8687294415237833, 'class_weight': 'balanced'}. Best is trial 22 with value: 0.8870857766262102.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_38_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/8a7cf6fec4f549039a5c4aa02fa74f23
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 09:53:55,607] Trial 38 finished with value: 0.8557207145779354 and parameters: {'C': 0.39259286160987394, 'l1_ratio': 0.9998611292536169, 'class_weight': None}. Best is trial 22 with value: 0.8870857766262102.


🏃 View run Trial_39_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/0a64ca2d08af4ef9b039ea14e5756342
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 09:54:59,154] Trial 39 finished with value: 0.7005318423564707 and parameters: {'C': 0.07277543704353365, 'l1_ratio': 0.7844541958411966, 'class_weight': None}. Best is trial 22 with value: 0.8870857766262102.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\metrics\_classification

🏃 View run Trial_40_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/0e7d6b807059458fbcf297d2a7b81b6b
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 09:56:26,170] Trial 40 finished with value: 0.34228828583117415 and parameters: {'C': 0.0001591362536415036, 'l1_ratio': 0.5756067778728995, 'class_weight': 'balanced'}. Best is trial 22 with value: 0.8870857766262102.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_41_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/e58da56b3c6e46239c98f9e188d28094
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 10:01:24,217] Trial 41 finished with value: 0.8776762580117278 and parameters: {'C': 0.7122840284518397, 'l1_ratio': 0.9523946739874064, 'class_weight': 'balanced'}. Best is trial 22 with value: 0.8870857766262102.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_42_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/fddbba17ba7f41e197982a352055b074
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 10:12:13,910] Trial 42 finished with value: 0.8765852993317879 and parameters: {'C': 1.5550613949707508, 'l1_ratio': 0.9063136292890847, 'class_weight': 'balanced'}. Best is trial 22 with value: 0.8870857766262102.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_43_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/36c6ae100c3c400f957ad8665f9c259f
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 10:16:34,322] Trial 43 finished with value: 0.8794490658666303 and parameters: {'C': 0.7380920640208719, 'l1_ratio': 0.9902758034012783, 'class_weight': 'balanced'}. Best is trial 22 with value: 0.8870857766262102.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_44_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/1117886d86434085bf8960838bc327b1
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 10:31:30,950] Trial 44 finished with value: 0.8633574253375154 and parameters: {'C': 3.2459739410682302, 'l1_ratio': 0.9046361258407453, 'class_weight': 'balanced'}. Best is trial 22 with value: 0.8870857766262102.


🏃 View run Trial_45_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/58fcc2b59c8a4a14aea9e1359bf21f4d
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 10:41:09,519] Trial 45 finished with value: 0.8183553797899904 and parameters: {'C': 0.2781128398147759, 'l1_ratio': 0.1466961018255028, 'class_weight': 'balanced'}. Best is trial 22 with value: 0.8870857766262102.


🏃 View run Trial_46_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/3836c26871b24400b57224f34daf4528
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 10:46:35,628] Trial 46 finished with value: 0.8694940679121779 and parameters: {'C': 0.705422958468485, 'l1_ratio': 0.8492221898148546, 'class_weight': 'balanced'}. Best is trial 22 with value: 0.8870857766262102.


🏃 View run Trial_47_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/0bd31509f095405eb85b990e15604e01
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 10:48:11,541] Trial 47 finished with value: 0.779762716487113 and parameters: {'C': 0.1443848627260826, 'l1_ratio': 0.9559582157778785, 'class_weight': None}. Best is trial 22 with value: 0.8870857766262102.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_48_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/883fe42fd29746e98f35dfb3a3ab9df5
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 10:55:09,177] Trial 48 finished with value: 0.8850402291013227 and parameters: {'C': 1.470580864473077, 'l1_ratio': 0.996647029149772, 'class_weight': None}. Best is trial 22 with value: 0.8870857766262102.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


🏃 View run Trial_49_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/8f722d27b3164ffca48d811c5bffa0cb
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14


[I 2026-07-22 11:11:15,284] Trial 49 finished with value: 0.8634937951725078 and parameters: {'C': 3.807554386583161, 'l1_ratio': 0.9050200434277258, 'class_weight': None}. Best is trial 22 with value: 0.8870857766262102.
C:\Users\Dell\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
2026/07/22 11:16:16 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/07/22 11:16:32 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html


🏃 View run Trial_Best_LogisticRegression_ at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14/runs/6757da8d437f4f29b9774f97bb1fbec5
🧪 View experiment at: https://dagshub.com/Roy7721/yt_comment_analysis.mlflow/#/experiments/14
[warn] optuna plots skipped: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Best accuracy: 0.8871
Best params  : {'C': 1.1199134843600127, 'l1_ratio': 0.9990014673384794, 'class_weight': None}


In [19]:
best_model

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators <combining_estimators>` for more details.","[('scaler', ...), ('clf', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing <metadata_routing>`.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
Name,Type,Value
"classes_ classes_: ndarray of shape (n_classes,)The classes labels. Only exist if the last step of the pipeline is aclassifier.","ndarray[int64](3,)","[-1, 0, 1]"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`. Only defined if theunderlying first estimator in `steps` exposes such an attributewhen fit... versionadded:: 0.24,int,10023
,"copy copy: bool, default=TrueSet to False to perform inplace scaling and avoid a copy (if the inputis already a numpy array).",True
,"clip clip: bool, default=FalseSet to True to clip transformed values of held-out data to [-1, 1].Since this parameter will clip values, `inverse_transform` may notbe able to restore the original data... note:: Setting `clip=True` does not prevent feature drift (a distribution shift between training and test data). The transformed values are clipped to the [-1, 1] range, which helps avoid unintended behavior in models sensitive to out-of-range inputs (e.g. linear models). Use with care, as clipping can distort the distribution of test data.",False
Name,Type,Value
"max_abs_ max_abs_: ndarray of shape (n_features,)Per feature maximum absolute value.","ndarray[float64](10023,)","[1. ,0.55,0.42,...,0.01,1. ,1. ]"


# 📌 Best Params — LogisticRegression + Custom Features

**Run:** 50/50 Optuna trials completed · ~500 minutes (~10 hours)
**Experiment (MLflow):** `LogisticRegression HP Tuning with Custom Features`
**Features:** TF-IDF bigram (1,2), `max_features=10000` + spaCy custom features (23 cols) → 10,023 total, kept **sparse** (9.7 MB vs ~2352 MB dense, 0.27% non-zero)
**Split:** 80/20, `random_state=42`, **no stratify** → 29,329 train / 7,333 test
**Scaler:** MaxAbsScaler (sparse-safe)

## 🏆 Best result

**Test accuracy: `0.8871`**

```python
best_params_logreg_custom = {
    'C':            1.1199134843600127,
    'l1_ratio':     0.9990014673384794,   # ~1.0 => essentially pure L1
    'class_weight': None,
    # fixed (not tuned)
    'solver':       'saga',
    'max_iter':     300,
    'random_state': 42,
}
```

Rebuild with:
```python
Pipeline([
    ('scaler', MaxAbsScaler()),
    ('clf', LogisticRegression(C=1.1199134843600127,
                               l1_ratio=0.9990014673384794,
                               class_weight=None,
                               solver='saga', max_iter=300, random_state=42))
])
```

## Full metrics

| Metric | Value |
|---|---|
| Accuracy | 0.8871 |
| Macro Precision | 0.8833 |
| Macro Recall | 0.8726 |
| **Macro F1** | **0.8756** |
| Weighted Precision | 0.8877 |
| Weighted Recall | 0.8871 |
| Weighted F1 | 0.8855 |
| -1 Precision / Recall / F1 | 0.8688 / 0.7596 / 0.8105 |
| 0 Precision / Recall / F1 | 0.8680 / 0.9721 / 0.9171 |
| 1 Precision / Recall / F1 | 0.9130 / 0.8860 / 0.8993 |

## Observations

- **`l1_ratio ≈ 0.999` means the winner is essentially pure L1 regularization.** This matters: earlier notebooks passed `penalty='l1'`, but on sklearn ≥1.8 `penalty` is deprecated and `l1_ratio` (default `0.0` = pure L2) silently takes precedence. So those runs actually trained **L2** despite asking for L1. This is the first run to genuinely use L1 — and L1 clearly won.
- **`class_weight=None` was selected** because the Optuna objective was **accuracy**. On imbalanced data, quietly under-serving the minority class is the cheapest way to raise accuracy. Visible in the results: strong class 0/1 scores, weakest recall on class -1 (0.7596).
- Tuning mattered far more than expected: trial 0 scored 0.8703, best reached **0.8871** (+1.68 accuracy, +1.78 macro F1).
- Keeping the matrix **sparse** was essential — the dense version could not finish a single trial in over an hour.

## ⚠️ Caveats before comparing with other experiments

1. **Different test rows.** This split has **no `stratify`**; `experiment_5_lor_with_hpt` uses `stratify=df['category']`. Same size (7,333) but *different comments* → ±0.5–1 point of split luck.
2. **Different regularization in practice.** exp_5 effectively trained L2 (see note above); this run trained true L1.
3. **Unequal trial budgets.** 50 trials here vs 30 in exp_5 — more attempts at the test set means more optimistic bias.
4. **Selected on the test set.** Optuna maximised accuracy *on this test set*, so `0.8871` is optimistic, not a clean generalisation estimate.

→ A fair verdict needs **both models trained on one shared split and scored on one shared held-out evaluation set.**
